# Generated by Django 5.1.2 on 2024-10-20 13:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField()),
                ('application_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('tenth_marks', models.FloatField()),
                ('twelfth_marks', models.FloatField()),
                ('graduation_marks', models.FloatField()),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('document', models.FileField(blank=True, null=True, upload_to='uploads/')),
            ],
        ),
    ]
